/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mitali;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mitali Sahoo
 */
public class Deposit extends javax.swing.JFrame {

    /**
     * Creates new form Deposit
     */
    public Deposit() {
        initComponents();
        getContentPane().setBackground(Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deposit3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        deposit2 = new javax.swing.JTextField();
        account1 = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        output1 = new javax.swing.JLabel();
        output = new javax.swing.JLabel();
        deposit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 750));
        setPreferredSize(new java.awt.Dimension(1350, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deposit3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        deposit3.setText("Enter amount to be deposited");
        getContentPane().add(deposit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, 46));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Account No");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 164, 41));

        account.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        account.setText("Amount");
        getContentPane().add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 164, 46));

        deposit2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deposit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deposit2MouseClicked(evt);
            }
        });
        deposit2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                deposit2KeyTyped(evt);
            }
        });
        getContentPane().add(deposit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 360, 60));

        account1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        account1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                account1KeyTyped(evt);
            }
        });
        getContentPane().add(account1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 360, 60));

        amount.setEditable(false);
        amount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 530, 360, 60));

        output1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        getContentPane().add(output1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 460, 80));

        output.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        getContentPane().add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 460, 80));

        deposit.setBackground(new java.awt.Color(0, 0, 0));
        deposit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deposit.setForeground(new java.awt.Color(255, 255, 255));
        deposit.setText("Deposit");
        deposit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deposit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositActionPerformed(evt);
            }
        });
        getContentPane().add(deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 650, 142, 53));

        clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        clear.setText("Clear");
        clear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 650, 138, 53));

        img.setBackground(java.awt.Color.gray);
        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back1.png"))); // NOI18N
        img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        img.setOpaque(true);
        img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgMouseClicked(evt);
            }
        });
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        
    }//GEN-LAST:event_amountActionPerformed

    private void deposit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deposit2MouseClicked
        
    }//GEN-LAST:event_deposit2MouseClicked

    private void account1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_account1KeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_account1KeyTyped

    private void deposit2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deposit2KeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_deposit2KeyTyped

    private void depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositActionPerformed
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
            }
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bank", "root", "");
            int acc,damt,amt = 0;
            acc=Integer.parseInt(account1.getText());
            PreparedStatement ps;
            String str="select * from account where account_no=?";
            ps=con.prepareStatement(str);
            ps.setInt(1,acc);
            ResultSet rs1=ps.executeQuery();
            int x=0;
            while(rs1.next())
            {
                x=rs1.getRow();
            }  
            if(x==0)
            {
                output.setText("This Account number doesn't exists!");
            }   
            else
            {
                damt=Integer.parseInt(deposit2.getText());
                
                amt=amt+damt;
                str="update account set amount=? where account_no=?";
                
                ps=con.prepareStatement(str);
                
                ps.setInt(1, amt);
                ps.setInt(2,acc);
                int i3=ps.executeUpdate();
                
                output1.setText("Rs "+damt+" is deposited");
                amount.setText(amt+"");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_depositActionPerformed

    private void imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMouseClicked
        this.setVisible(false);
        new Project().setVisible(true);
    }//GEN-LAST:event_imgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account;
    private javax.swing.JTextField account1;
    private javax.swing.JTextField amount;
    private javax.swing.JButton clear;
    private javax.swing.JButton deposit;
    private javax.swing.JTextField deposit2;
    private javax.swing.JLabel deposit3;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel output;
    private javax.swing.JLabel output1;
    // End of variables declaration//GEN-END:variables
}
