/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mitali;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mitali Sahoo
 */
public class Transfer extends javax.swing.JFrame {

    /**
     * Creates new form Transfer
     */
    public Transfer() {
        initComponents();
        getContentPane().setBackground(Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        to = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        to1 = new javax.swing.JLabel();
        accountfrom = new javax.swing.JTextField();
        accountto = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        result1 = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 750));
        setPreferredSize(new java.awt.Dimension(1350, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        to.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        to.setText("To Account No");
        getContentPane().add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 224, 51));

        from.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        from.setText("From Account No");
        getContentPane().add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 212, 51));

        result.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 490, 90));

        to1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        to1.setText("Amount to be transferred");
        getContentPane().add(to1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 280, 51));

        accountfrom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        accountfrom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accountfromKeyTyped(evt);
            }
        });
        getContentPane().add(accountfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 380, 70));

        accountto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        accountto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accounttoKeyTyped(evt);
            }
        });
        getContentPane().add(accountto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 380, 70));

        amount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountKeyTyped(evt);
            }
        });
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 380, 70));
        getContentPane().add(result1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 398, 47));

        button.setBackground(new java.awt.Color(0, 0, 0));
        button.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Transfer");
        button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 610, 121, 46));

        img.setBackground(java.awt.Color.gray);
        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back1.png"))); // NOI18N
        img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        img.setOpaque(true);
        img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgMouseClicked(evt);
            }
        });
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void accountfromKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountfromKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_accountfromKeyTyped

    private void accounttoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accounttoKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_accounttoKeyTyped

    private void amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_amountKeyTyped

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Transfer.class.getName()).log(Level.SEVERE, null, ex);
            }
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bank", "root", "");
            int accto,accfrom,amtto = 0,tramt=0,amtfrom=0;
            tramt=Integer.parseInt(amount.getText());
           
            accfrom=Integer.parseInt(accountfrom.getText());
            PreparedStatement ps;
            String str="select * from account where account_no=?";
            ps=con.prepareStatement(str);
            ps.setInt(1,accfrom);
            ResultSet rs1=ps.executeQuery();
            int x=0;
            rs1.next();
            x=rs1.getRow();
              
            if(x==0)
            {
                result.setText("From Account number doesn't exists!");
            }   
            else
            {
                amtfrom=Integer.parseInt(rs1.getString(9));
                
                accto=Integer.parseInt(accountto.getText());
                
                str="select * from account where account_no=?";
                ps=con.prepareStatement(str);
                ps.setInt(1, accto);
                ResultSet rs=ps.executeQuery();
                x=0;
                
                rs.next();
                x=rs.getRow();
                 
                if(x==0)
                {
                    result.setText("To Account number doesn't exists!");
                }   
                else
                {
                    
                    if((amtfrom-tramt)>500)
                    {
                        amtfrom=amtfrom-tramt;
                        str="update account set amount=? where account_no=?";
                    
                        ps=con.prepareStatement(str);

                        ps.setInt(1, amtfrom);
                        ps.setInt(2,accfrom);
                        int i3=ps.executeUpdate();
                        
                        amtto=amtto+tramt;
                        str="update account set amount=? where account_no=?";
                    
                        ps=con.prepareStatement(str);

                        ps.setInt(1, amtto);
                        ps.setInt(2,accto);
                        int i4=ps.executeUpdate();

                        result1.setText("Rs "+tramt+" is transferred");
                        
                    }
                    else
                    {
                        result1.setText("Transfer failed due to insuffucient balance");
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Transfer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMouseClicked
        this.setVisible(false);
        new Project().setVisible(true);
    }//GEN-LAST:event_imgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountfrom;
    private javax.swing.JTextField accountto;
    private javax.swing.JTextField amount;
    private javax.swing.JButton button;
    private javax.swing.JLabel from;
    private javax.swing.JLabel img;
    private javax.swing.JLabel result;
    private javax.swing.JLabel result1;
    private javax.swing.JLabel to;
    private javax.swing.JLabel to1;
    // End of variables declaration//GEN-END:variables
}
