/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mitali;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mitali Sahoo
 */
public class Withdraw extends javax.swing.JFrame {

    /**
     * Creates new form Withdraw
     */
    public Withdraw() {
        initComponents();
        getContentPane().setBackground(Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        account = new javax.swing.JLabel();
        withdraw = new javax.swing.JLabel();
        result2 = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        withdraw1 = new javax.swing.JTextField();
        account1 = new javax.swing.JTextField();
        amount1 = new javax.swing.JTextField();
        result1 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 750));
        setPreferredSize(new java.awt.Dimension(1350, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        account.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        account.setText("Account no");
        getContentPane().add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 179, 45));

        withdraw.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        withdraw.setText("Enter Amount to be withdrawn");
        getContentPane().add(withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, 45));

        result2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        getContentPane().add(result2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 480, 70));

        amount.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        amount.setText("Amount ");
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 179, 45));

        withdraw1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        withdraw1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withdraw1MouseClicked(evt);
            }
        });
        withdraw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdraw1ActionPerformed(evt);
            }
        });
        withdraw1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                withdraw1KeyTyped(evt);
            }
        });
        getContentPane().add(withdraw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 383, 60));

        account1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        account1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                account1KeyTyped(evt);
            }
        });
        getContentPane().add(account1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 383, 60));

        amount1.setEditable(false);
        amount1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount1ActionPerformed(evt);
            }
        });
        getContentPane().add(amount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 383, 60));

        result1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        getContentPane().add(result1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 480, 70));

        submit.setBackground(new java.awt.Color(0, 0, 0));
        submit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Withdraw");
        submit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.setOpaque(true);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, 150, 60));

        clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        clear.setText("Clear");
        clear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear.setContentAreaFilled(false);
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, 160, 60));

        img.setBackground(java.awt.Color.gray);
        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back1.png"))); // NOI18N
        img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        img.setOpaque(true);
        img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgMouseClicked(evt);
            }
        });
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void account1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_account1KeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_account1KeyTyped

    private void withdraw1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_withdraw1KeyTyped
       char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_withdraw1KeyTyped

    private void amount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount1ActionPerformed
        
    }//GEN-LAST:event_amount1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        account1.setText("");
        result1.setText("");
        result2.setText("");
        withdraw1.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void withdraw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdraw1ActionPerformed

    }//GEN-LAST:event_withdraw1ActionPerformed

    private void withdraw1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdraw1MouseClicked
        
    }//GEN-LAST:event_withdraw1MouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
         try {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
            }
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bank", "root", "");
            int acc,wamt,amt = 0;
            acc=Integer.parseInt(account1.getText());
            PreparedStatement ps;
            String str="select * from account where account_no=?";
            ps=con.prepareStatement(str);
            ps.setInt(1,acc);
            ResultSet rs1=ps.executeQuery();
            int x=0;
            while(rs1.next())
            {
                x=rs1.getRow();
            }  
            if(x==0)
            {
                result1.setText("This Account number doesn't exists!");
            }   
            else
            {
                wamt=Integer.parseInt(withdraw1.getText());
                str="select * from account where account_no=?";
                ps=con.prepareStatement(str);
                ps.setInt(1, acc);
                rs1=ps.executeQuery();
                while(rs1.next())
                {
                    amt=Integer.parseInt(rs1.getString(9));
                }
                if(amt-wamt<=500)
                {
                    result1.setText("Not enough money for transaction");
                }
                else
                {
                    amt=amt-wamt;
                    str="update account set amount=? where account_no=?";
                    
                    ps=con.prepareStatement(str);
                    
                    ps.setInt(1, amt);
                    ps.setInt(2,acc);
                    int i3=ps.executeUpdate();
                    
                    result2.setText("Rs "+wamt+" is withdrawn");
                    amount1.setText(amt+"");
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_submitActionPerformed

    private void imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMouseClicked
        this.setVisible(false);
        new Project().setVisible(true);
    }//GEN-LAST:event_imgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account;
    private javax.swing.JTextField account1;
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amount1;
    private javax.swing.JButton clear;
    private javax.swing.JLabel img;
    private javax.swing.JLabel result1;
    private javax.swing.JLabel result2;
    private javax.swing.JButton submit;
    private javax.swing.JLabel withdraw;
    private javax.swing.JTextField withdraw1;
    // End of variables declaration//GEN-END:variables
}
